import Image from "next/image";

const reviews = [
{
  id: 1,
  rating: 5,
  comment: "Hasil sablon sangat rapi dan pengiriman cepat.",
  image: "/assets/hasilSablon/hasilsablon4.jpg",
  name: "Andi Saputra",
  product: "Topi",
  city: "Bandung",
  orderDate: "2026-07-20",
},
{
  id: 2,
  rating: 4,
  comment: "Hasil sablon sangat rapi dan pengiriman cepat.",
  image: "/assets/hasilSablon/hasilsablon3.jpg",
  name: "Aji Saputro",
  product: "Kaos",
  city: "Depok",
  orderDate: "2026-07-20",
},
{
  id: 3,
  rating: 5,
  comment: "Hasil sablon sangat rapi dan pengiriman cepat.",
  image: "/assets/hasilSablon/hasilsablon1.jpg",
  name: "Ani Saputri",
  product: "Kaos",
  city: "Bandung",
  orderDate: "2026-07-20",
},
{
  id: 4,
  rating: 4,
  comment: "Hasil sablon sangat rapi dan pengiriman cepat.",
  image: "/assets/hasilSablon/hasilsablon2.jpg",
  name: "Adi putra",
  product: "Toth Bag",
  city: "Bekasi",
  orderDate: "2026-07-20",
},
{
  id: 5,
  rating: 4,
  comment: "Hasil sablon sangat rapi dan pengiriman cepat.",
  image: "/assets/hasilSablon/hasilsablon2.jpg",
  name: "Adi putra",
  product: "Toth Bag",
  city: "Bekasi",
  orderDate: "2026-07-20",
},
{
  id: 6,
  rating: 4,
  comment: "Hasil sablon sangat rapi dan pengiriman cepat.",
  image: "/assets/hasilSablon/hasilsablon2.jpg",
  name: "Adi putra",
  product: "Toth Bag",
  city: "Bekasi",
  orderDate: "2026-07-20",
},
{
  id: 7,
  rating: 4,
  comment: "Hasil sablon sangat rapi dan pengiriman cepat.",
  image: "/assets/hasilSablon/hasilsablon2.jpg",
  name: "Adi putra",
  product: "Toth Bag",
  city: "Bekasi",
  orderDate: "2026-07-20",
},
];
export default reviews ;